In [75]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [76]:
googleplayclean = pd.read_csv('C:/Users/davyn/Downloads/googleplayclean.csv')
# dependent variable
y = googleplayclean[['Success']]
# independent variables
x = googleplayclean[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

In [77]:
puzzle = googleplayclean.copy()
arcade = googleplayclean.copy()
casual = googleplayclean.copy()
sim = googleplayclean.copy()
action = googleplayclean.copy()
adv = googleplayclean.copy()

# Using Naive Bayes on Whole Dataset

In [91]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix = \n{}".format(cm))
ac = accuracy_score(y_test, y_pred)
print("Accuracy Score = {}".format(ac))
print("FPR = {}".format(33553/(33553+14)))
print("TPR = {}".format(67/(67+2867)))

Confusion Matrix = 
[[33553    14]
 [ 2867    67]]
Accuracy Score = 0.9210706555984768
FPR = 0.9995829237048292
TPR = 0.02283571915473756


C:\Users\davyn\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Using Naive Bayes on Puzzle Games

In [79]:
puzzle_0 = ['Puzzle']
puzzleNotExist = ~puzzle['Category'].isin(puzzle_0)
puzzleNotExist_rows = puzzle[puzzleNotExist]
puzzle = puzzle.drop(puzzleNotExist_rows.index)

# dependent variable
yP = puzzle[['Success']]
# independent variables
xP = puzzle[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

In [92]:
# Splitting the Dataset
xP_train, xP_test, yP_train, yP_test = train_test_split(xP, yP, test_size = 0.2, random_state = 0)

# Feature Scaling
xP_train = sc.fit_transform(xP_train)
xP_test = sc.transform(xP_test)

# Training the Naive Bayes Model on the training set
classifier.fit(xP_train, yP_train)

# Predicting Test Results
yP_pred = classifier.predict(xP_test)

cmP = confusion_matrix(yP_test, yP_pred)
print("Confusion Matrix = \n{}".format(cmP))
acP = accuracy_score(yP_test, yP_pred)
print("Accuracy Score = {}".format(acP))
print("FPR = {}".format(5114/(5114+476)))
print("TPR = {}".format(163/(163+237)))

Confusion Matrix = 
[[5114  476]
 [ 237  163]]
Accuracy Score = 0.8809682804674458
FPR = 0.9148479427549195
TPR = 0.4075


C:\Users\davyn\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


 # Using Naive Bayes on Arcade Games

In [81]:
arcade_0 = ['Arcade']
arcadeNotExist = ~arcade['Category'].isin(arcade_0)
arcadeNotExist_rows = arcade[arcadeNotExist]
arcade = arcade.drop(arcadeNotExist_rows.index)

# dependent variable
yAr = arcade[['Success']]
# independent variables
xAr = arcade[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

In [93]:
# Splitting the Dataset
xAr_train, xAr_test, yAr_train, yAr_test = train_test_split(xAr, yAr, test_size = 0.2, random_state = 0)

# Feature Scaling
xAr_train = sc.fit_transform(xAr_train)
xAr_test = sc.transform(xAr_test)

# Training the Naive Bayes Model on the training set
classifier.fit(xAr_train, yAr_train)

# Predicting Test Results
yAr_pred = classifier.predict(xAr_test)

cmAr = confusion_matrix(yAr_test, yAr_pred)
print("Confusion Matrix = \n{}".format(cmAr))
acAr = accuracy_score(yAr_test, yAr_pred)
print("Accuracy Score = {}".format(acAr))
print("FPR = {}".format(5588/(5588+0)))
print("TPR = {}".format(3/(3+245)))

Confusion Matrix = 
[[5588    0]
 [ 245    3]]
Accuracy Score = 0.9580191912268677
FPR = 1.0
TPR = 0.012096774193548387


C:\Users\davyn\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Using Naive Bayes on Casual Games

In [83]:
casual_0 = ['Casual']
casualNotExist = ~casual['Category'].isin(casual_0)
casualNotExist_rows = casual[casualNotExist]
casual = casual.drop(casualNotExist_rows.index)

# dependent variable
yC = casual[['Success']]
# independent variables
xC = casual[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

In [94]:
# Splitting the Dataset
xC_train, xC_test, yC_train, yC_test = train_test_split(xC, yC, test_size = 0.2, random_state = 0)

# Feature Scaling
xC_train = sc.fit_transform(xC_train)
xC_test = sc.transform(xC_test)

# Training the Naive Bayes Model on the training set
classifier.fit(xC_train, yC_train)

# Predicting Test Results
yC_pred = classifier.predict(xC_test)

cmC = confusion_matrix(yC_test, yC_pred)
print("Confusion Matrix = \n{}".format(cmC))
acC = accuracy_score(yC_test, yC_pred)
print("Accuracy Score = {}".format(acC))
print("FPR = {}".format(4728/(4728+335)))
print("TPR = {}".format(158/(158+286)))

Confusion Matrix = 
[[4728  335]
 [ 286  158]]
Accuracy Score = 0.8872344289086617
FPR = 0.9338336954374876
TPR = 0.35585585585585583


C:\Users\davyn\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Using Naive Bayes on Simulation Games

In [85]:
sim_0 = ['Simulation']
simNotExist = ~sim['Category'].isin(sim_0)
simNotExist_rows = sim[simNotExist]
sim = sim.drop(simNotExist_rows.index)

# dependent variable
yS = sim[['Success']]
# independent variables
xS = sim[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

In [95]:
# Splitting the Dataset
xS_train, xS_test, yS_train, yS_test = train_test_split(xS, yS, test_size = 0.2, random_state = 0)

# Feature Scaling
xS_train = sc.fit_transform(xS_train)
xS_test = sc.transform(xS_test)

# Training the Naive Bayes Model on the training set
classifier.fit(xS_train, yS_train)

# Predicting Test Results
yS_pred = classifier.predict(xS_test)

cmS = confusion_matrix(yS_test, yS_pred)
print("Confusion Matrix = \n{}".format(cmS))
acS = accuracy_score(yS_test, yS_pred)
print("Accuracy Score = {}".format(acS))
print("FPR = {}".format(3256/(3256+0)))
print("TPR = {}".format(16/(16+366)))

Confusion Matrix = 
[[3256    0]
 [ 366   16]]
Accuracy Score = 0.8993952721275426
FPR = 1.0
TPR = 0.041884816753926704


C:\Users\davyn\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Using Naive Bayes on Action Games

In [87]:
action_0 = ['Action']
actionNotExist = ~action['Category'].isin(action_0)
actionNotExist_rows = action[actionNotExist]
action = action.drop(actionNotExist_rows.index)

# dependent variable
yA = action[['Success']]
# independent variables
xA = action[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

In [96]:
# Splitting the Dataset
xA_train, xA_test, yA_train, yA_test = train_test_split(xA, yA, test_size = 0.2, random_state = 0)

# Feature Scaling
xA_train = sc.fit_transform(xA_train)
xA_test = sc.transform(xA_test)

# Training the Naive Bayes Model on the training set
classifier.fit(xA_train, yA_train)

# Predicting Test Results
yA_pred = classifier.predict(xA_test)

cmA = confusion_matrix(yA_test, yA_pred)
print("Confusion Matrix = \n{}".format(cmA))
acA = accuracy_score(yA_test, yA_pred)
print("Accuracy Score = {}".format(acA))
print("FPR = {}".format(3101/(3101+0)))
print("TPR = {}".format(8/(8+310)))

Confusion Matrix = 
[[3101    0]
 [ 310    8]]
Accuracy Score = 0.909330213512723
FPR = 1.0
TPR = 0.025157232704402517


C:\Users\davyn\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Using Naive Bayes on Adventure Games

In [89]:
adv_0 = ['Adventure']
advNotExist = ~adv['Category'].isin(adv_0)
advNotExist_rows = adv[advNotExist]
adv = adv.drop(advNotExist_rows.index)

# dependent variable
yAdv = adv[['Success']]
# independent variables
xAdv = adv[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

In [97]:
# Splitting the Dataset
xAdv_train, xAdv_test, yAdv_train, yAdv_test = train_test_split(xAdv, yAdv, test_size = 0.2, random_state = 0)

# Feature Scaling
xAdv_train = sc.fit_transform(xAdv_train)
xAdv_test = sc.transform(xAdv_test)

# Training the Naive Bayes Model on the training set
classifier.fit(xAdv_train, yAdv_train)

# Predicting Test Results
yAdv_pred = classifier.predict(xAdv_test)

cmAdv = confusion_matrix(yAdv_test, yAdv_pred)
print("Confusion Matrix = \n{}".format(cmAdv))
acAdv = accuracy_score(yAdv_test, yAdv_pred)
print("Accuracy Score = {}".format(acAdv))
print("FPR = {}".format(2831/(2831+3)))
print("TPR = {}".format(5/(5+160)))

Confusion Matrix = 
[[2831    3]
 [ 160    5]]
Accuracy Score = 0.9456485495165055
FPR = 0.9989414255469301
TPR = 0.030303030303030304


C:\Users\davyn\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
