In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
import math
from sklearn.ensemble import AdaBoostClassifier
ad = AdaBoostClassifier()

In [2]:
googleplayclean = pd.read_csv('C:/Users/davyn/OneDrive/Documents/GitHub/play-store-analysis/googleplayclean.csv')

In [3]:
puzzle = googleplayclean.copy()
arcade = googleplayclean.copy()
casual = googleplayclean.copy()
sim = googleplayclean.copy()
action = googleplayclean.copy()
adv = googleplayclean.copy()

# Using Adaboost on Whole Dataset

In [4]:
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
for var in cat_vars:
    cat_list = 'var'+'_'+var
    cat_list = pd.get_dummies(googleplayclean[var], prefix=var)
    data1 = googleplayclean.join(cat_list)
    googleplayclean = data1
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
data_vars = googleplayclean.columns.values.tolist()
to_keep = [i for i in data_vars if i not in cat_vars]
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
data_vars = googleplayclean.columns.values.tolist()
to_keep = [i for i in data_vars if i not in cat_vars]

In [5]:
# dependent variable
y = googleplayclean[['Success']]
# independent variables
x = googleplayclean[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

os = SMOTE(random_state = 0)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)
columns = x_train.columns

smote_data_x, smote_data_y = os.fit_resample(x_train, y_train)
smote_data_x = pd.DataFrame(data = smote_data_x, columns = columns)
smote_data_y = pd.DataFrame(data = smote_data_y, columns = ['Success'])

In [6]:
# make a list of all independent features
feature_names = smote_data_x.columns.to_list()
model = ad.fit(googleplayclean[feature_names].values, googleplayclean["Success"].values)
# get the scores
score = model.score(googleplayclean[feature_names].values, googleplayclean['Success'].values)
print("Model Score = {}".format(score))


Model Score = 0.9229323514262857


In [7]:
# create the X with all important features only
x = smote_data_x[feature_names]
y = smote_data_y['Success']

In [8]:
x = pd.get_dummies(x, columns=['Free', 'Ad Supported', 'In App Purchases', 'Editors Choice'], drop_first=True)

In [9]:
#Split the dataset to test and train data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
y_pred = ad.fit(x_train, y_train).predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix = \n{}".format(cm))
ac = accuracy_score(y_test, y_pred)
print("Accuracy Score = {}".format(ac))
print("TNR = {}".format(19547/(19547+7381)))
print("TPR = {}".format(20762/(20762+6140)))

Confusion Matrix = 
[[19547  7381]
 [ 6140 20762]]
Accuracy Score = 0.7488203603938325
TNR = 0.7258986928104575
TPR = 0.7717641811017768


# Using Adaboost on Puzzle Games

In [10]:
puzzle_0 = ['Puzzle']
puzzleNotExist = ~puzzle['Category'].isin(puzzle_0)
puzzleNotExist_rows = puzzle[puzzleNotExist]
puzzle = puzzle.drop(puzzleNotExist_rows.index)

In [11]:
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
for var in cat_vars:
    cat_list = 'var'+'_'+var
    cat_list = pd.get_dummies(puzzle[var], prefix=var)
    data1 = puzzle.join(cat_list)
    puzzle = data1
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
data_vars = puzzle.columns.values.tolist()
to_keep = [i for i in data_vars if i not in cat_vars]

In [12]:
# dependent variable
yP = puzzle[['Success']]
# independent variables
xP = puzzle[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

osP = SMOTE(random_state = 0)
xP_train, xP_test, yP_train, yP_test = train_test_split(xP, yP, test_size = 0.2, random_state=0)
columnsP = xP_train.columns

smote_data_xP, smote_data_yP = osP.fit_resample(xP_train, yP_train)
smote_data_xP = pd.DataFrame(data = smote_data_xP, columns = columnsP)
smote_data_yP = pd.DataFrame(data = smote_data_yP, columns = ['Success'])

# make a list of all independent features
feature_namesP = smote_data_xP.columns.to_list()
modelP = ad.fit(puzzle[feature_names].values, puzzle["Success"].values)
# get the scores
scoreP = modelP.score(puzzle[feature_names].values, puzzle['Success'].values)
print("Model Score = {}".format(scoreP))

# create the X with all important features only
xP = smote_data_xP[feature_names]
yP = smote_data_yP['Success']

xP = pd.get_dummies(xP, columns=['Free', 'Ad Supported', 'In App Purchases', 'Editors Choice'], drop_first=True)

# Splitting the Dataset
xP_train, xP_test, yP_train, yP_test = train_test_split(xP, yP, test_size = 0.2, random_state = 0)
yP_pred = ad.fit(xP_train, yP_train).predict(xP_test)
cmP = confusion_matrix(yP_test, yP_pred)
print("Confusion Matrix = \n{}".format(cmP))
acP = accuracy_score(yP_test, yP_pred)
print("Accuracy Score = {}".format(acP))
print("TNR = {}".format(3340/(3340+1141)))
print("TPR = {}".format(3741/(3741+747)))

Model Score = 0.9368530020703933
Confusion Matrix = 
[[3340 1141]
 [ 747 3741]]
Accuracy Score = 0.7894971568736759
TNR = 0.7453693372015175
TPR = 0.8335561497326203


# Using AdaBoost on Arcade Games

In [13]:
arcade_0 = ['Arcade']
arcadeNotExist = ~arcade['Category'].isin(arcade_0)
arcadeNotExist_rows = arcade[arcadeNotExist]
arcade = arcade.drop(arcadeNotExist_rows.index)

In [14]:
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
for var in cat_vars:
    cat_list = 'var'+'_'+var
    cat_list = pd.get_dummies(arcade[var], prefix=var)
    data1 = arcade.join(cat_list)
    arcade = data1
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
data_vars = arcade.columns.values.tolist()
to_keep = [i for i in data_vars if i not in cat_vars]

In [15]:
# dependent variable
yAr = arcade[['Success']]
# independent variables
xAr = arcade[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

osAr = SMOTE(random_state = 0)
xAr_train, xAr_test, yAr_train, yAr_test = train_test_split(xAr, yAr, test_size = 0.2, random_state=0)
columnsAr= xAr_train.columns

smote_data_xAr, smote_data_yAr = osAr.fit_resample(xAr_train, yAr_train)
smote_data_xAr = pd.DataFrame(data = smote_data_xAr, columns = columnsAr)
smote_data_yAr = pd.DataFrame(data = smote_data_yAr, columns = ['Success'])

# make a list of all independent features
feature_namesAr = smote_data_xAr.columns.to_list()
modelAr = ad.fit(casual[feature_namesAr].values, casual["Success"].values)
# get the scores
scoreAr = modelAr.score(casual[feature_namesAr].values, casual['Success'].values)
print("Model Score = {}".format(scoreAr))

# create the X with all important features only
xAr = smote_data_xAr[feature_names]
yAr = smote_data_yAr['Success']

xAr = pd.get_dummies(xAr, columns=['Free', 'Ad Supported', 'In App Purchases', 'Editors Choice'], drop_first=True)

# Splitting the Dataset
xAr_train, xAr_test, yAr_train, yAr_test = train_test_split(xAr, yAr, test_size = 0.2, random_state = 0)
yAr_pred = ad.fit(xAr_train, yAr_train).predict(xAr_test)
cmAr = confusion_matrix(yAr_test, yAr_pred)
print("Confusion Matrix = \n{}".format(cmAr))
acAr = accuracy_score(yAr_test, yAr_pred)
print("Accuracy Score = {}".format(acAr))
print("TNR = {}".format(3513/(3513+921)))
print("TPR = {}".format(3844/(3844+600)))

Model Score = 0.9229323514262857
Confusion Matrix = 
[[3513  921]
 [ 600 3844]]
Accuracy Score = 0.8286776300968687
TNR = 0.7922868741542625
TPR = 0.864986498649865


# Using AdaBoost on Casual Games

In [16]:
casual_0 = ['Casual']
casualNotExist = ~casual['Category'].isin(casual_0)
casualNotExist_rows = casual[casualNotExist]
casual = casual.drop(casualNotExist_rows.index)

cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
for var in cat_vars:
    cat_list = 'var'+'_'+var
    cat_list = pd.get_dummies(casual[var], prefix=var)
    data1 = casual.join(cat_list)
    casual = data1
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
data_vars = casual.columns.values.tolist()
to_keep = [i for i in data_vars if i not in cat_vars]

# dependent variable
yC = casual[['Success']]
# independent variables
xC = casual[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]
osC = SMOTE(random_state = 0)
xC_train, xC_test, yC_train, yC_test = train_test_split(xC, yC, test_size = 0.2, random_state=0)
columnsC = xC_train.columns

smote_data_xC, smote_data_yC = osC.fit_resample(xC_train, yC_train)
smote_data_xC = pd.DataFrame(data = smote_data_xC, columns = columnsC)
smote_data_yC = pd.DataFrame(data = smote_data_yC, columns = ['Success'])

# make a list of all independent features
feature_namesC = smote_data_xC.columns.to_list()
modelC = ad.fit(casual[feature_names].values, casual["Success"].values)
# get the scores
scoreC = modelC.score(casual[feature_namesC].values, casual['Success'].values)
print("Model Score = {}".format(scoreC))

# create the X with all important features only
xC = smote_data_xC[feature_namesC]
yC = smote_data_yC['Success']
xC = pd.get_dummies(xC, columns=['Free', 'Ad Supported', 'In App Purchases', 'Editors Choice'], drop_first=True)

# Splitting the Dataset
xC_train, xC_test, yC_train, yC_test = train_test_split(xC, yC, test_size = 0.2, random_state = 0)
yC_pred = ad.fit(xC_train, yC_train).predict(xC_test)
cmC = confusion_matrix(yC_test, yC_pred)
print("Confusion Matrix = \n{}".format(cmC))
acC = accuracy_score(yC_test, yC_pred)
print("Accuracy Score = {}".format(acC))
print("TNR = {}".format(3046/(3046+1030)))
print("TPR = {}".format(3176/(3176+901)))

Model Score = 0.9255048670637803
Confusion Matrix = 
[[3046 1030]
 [ 901 3176]]
Accuracy Score = 0.7631546669937447
TNR = 0.7473012757605496
TPR = 0.7790041697326465


# Using AdaBoost on Simulation Games

In [17]:
sim_0 = ['Simulation']
simNotExist = ~sim['Category'].isin(sim_0)
simNotExist_rows = sim[simNotExist]
sim = sim.drop(simNotExist_rows.index)

cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
for var in cat_vars:
    cat_list = 'var'+'_'+var
    cat_list = pd.get_dummies(sim[var], prefix=var)
    data1 = sim.join(cat_list)
    sim = data1
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
data_vars = sim.columns.values.tolist()
to_keep = [i for i in data_vars if i not in cat_vars]

# dependent variable
yS = sim[['Success']]
# independent variables
xS = sim[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

osS = SMOTE(random_state = 0)
xS_train, xS_test, yS_train, yS_test = train_test_split(xS, yS, test_size = 0.2, random_state=0)
columnsS = xS_train.columns

smote_data_xS, smote_data_yS = osS.fit_resample(xS_train, yS_train)
smote_data_xS = pd.DataFrame(data = smote_data_xS, columns = columnsS)
smote_data_yS = pd.DataFrame(data = smote_data_yS, columns = ['Success'])

# make a list of all independent features
feature_namesS = smote_data_xS.columns.to_list()
modelS = ad.fit(sim[feature_names].values, sim["Success"].values)
# get the scores
scoreS = modelS.score(sim[feature_namesS].values, sim['Success'].values)
print("Model Score = {}".format(scoreS))

# create the X with all important features only
xS = smote_data_xS[feature_namesS]
yS = smote_data_yS['Success']
xS = pd.get_dummies(xS, columns=['Free', 'Ad Supported', 'In App Purchases', 'Editors Choice'], drop_first=True)

# Splitting the Dataset
xS_train, xS_test, yS_train, yS_test = train_test_split(xS, yS, test_size = 0.2, random_state = 0)
yS_pred = ad.fit(xS_train, yS_train).predict(xS_test)
cmS = confusion_matrix(yS_test, yS_pred)
print("Confusion Matrix = \n{}".format(cmS))
acS = accuracy_score(yS_test, yS_pred)
print("Accuracy Score = {}".format(acS))
print("TNR = {}".format(1830/(1830+725)))
print("TPR = {}".format(2066/(2066+570)))

Model Score = 0.8954370533260033
Confusion Matrix = 
[[1830  725]
 [ 570 2066]]
Accuracy Score = 0.7505297630514352
TNR = 0.7162426614481409
TPR = 0.783763277693475


# Using AdaBoost on Action Games

In [18]:
action_0 = ['Action']
actionNotExist = ~action['Category'].isin(action_0)
actionNotExist_rows = action[actionNotExist]
action = action.drop(actionNotExist_rows.index)

cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
for var in cat_vars:
    cat_list = 'var'+'_'+var
    cat_list = pd.get_dummies(action[var], prefix=var)
    data1 = action.join(cat_list)
    action = data1
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
data_vars = action.columns.values.tolist()
to_keep = [i for i in data_vars if i not in cat_vars]

# dependent variable
yA = action[['Success']]
# independent variables
xA = action[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

osA = SMOTE(random_state = 0)
xA_train, xA_test, yA_train, yA_test = train_test_split(xA, yA, test_size = 0.2, random_state=0)
columnsA = xA_train.columns

smote_data_xA, smote_data_yA = osA.fit_resample(xA_train, yA_train)
smote_data_xA = pd.DataFrame(data = smote_data_xA, columns = columnsA)
smote_data_yA = pd.DataFrame(data = smote_data_yA, columns = ['Success'])

# make a list of all independent features
feature_namesA = smote_data_xA.columns.to_list()
modelA = ad.fit(action[feature_names].values, action["Success"].values)
# get the scores
scoreA = modelA.score(action[feature_namesA].values, action['Success'].values)
print("Model Score = {}".format(scoreA))

# create the X with all important features only
xA = smote_data_xA[feature_namesA]
yA = smote_data_yA['Success']
xA = pd.get_dummies(xA, columns=['Free', 'Ad Supported', 'In App Purchases', 'Editors Choice'], drop_first=True)

# Splitting the Dataset
xA_train, xA_test, yA_train, yA_test = train_test_split(xA, yA, test_size = 0.2, random_state = 0)
yA_pred = ad.fit(xA_train, yA_train).predict(xA_test)
cmA = confusion_matrix(yA_test, yA_pred)
print("Confusion Matrix = \n{}".format(cmA))
acA = accuracy_score(yA_test, yA_pred)
print("Accuracy Score = {}".format(acA))
print("TNR = {}".format(1788/(1788+675)))
print("TPR = {}".format(2105/(2105+358)))

Model Score = 0.905054405054405
Confusion Matrix = 
[[1788  675]
 [ 358 2105]]
Accuracy Score = 0.7902963865205035
TNR = 0.7259439707673568
TPR = 0.85464880227365


# Using AdaBoost on Adventure Games

In [19]:
adv_0 = ['Adventure']
advNotExist = ~adv['Category'].isin(adv_0)
advNotExist_rows = adv[advNotExist]
adv = adv.drop(advNotExist_rows.index)

cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
for var in cat_vars:
    cat_list = 'var'+'_'+var
    cat_list = pd.get_dummies(adv[var], prefix=var)
    data1 = adv.join(cat_list)
    adv = data1
cat_vars=['Free', 'Size', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']
data_vars = adv.columns.values.tolist()
to_keep = [i for i in data_vars if i not in cat_vars]

# dependent variable
yAdv = adv[['Success']]
# independent variables
xAdv = adv[['Free', 'Price', 'Ad Supported', 'In App Purchases', 'Editors Choice', 'Time Gap']]

osAdv = SMOTE(random_state = 0)
xAdv_train, xAdv_test, yAdv_train, yAdv_test = train_test_split(xAdv, yAdv, test_size = 0.2, random_state=0)
columnsAdv = xAdv_train.columns

smote_data_xAdv, smote_data_yAdv = osAdv.fit_resample(xAdv_train, yAdv_train)
smote_data_xAdv = pd.DataFrame(data = smote_data_xAdv, columns = columnsAdv)
smote_data_yAdv = pd.DataFrame(data = smote_data_yAdv, columns = ['Success'])

# make a list of all independent features
feature_namesAdv = smote_data_xAdv.columns.to_list()
modelAdv = ad.fit(adv[feature_names].values, adv["Success"].values)
# get the scores
scoreAdv = modelAdv.score(action[feature_namesAdv].values, action['Success'].values)
print("Model Score = {}".format(scoreAdv))

# create the X with all important features only
xAdv = smote_data_xAdv[feature_namesAdv]
yAdv = smote_data_yAdv['Success']
xAdv = pd.get_dummies(xAdv, columns=['Free', 'Ad Supported', 'In App Purchases', 'Editors Choice'], drop_first=True)

# Splitting the Dataset
xAdv_train, xAdv_test, yAdv_train, yAdv_test = train_test_split(xAdv, yAdv, test_size = 0.2, random_state = 0)
yAdv_pred = ad.fit(xAdv_train, yAdv_train).predict(xAdv_test)
cmAdv = confusion_matrix(yAdv_test, yAdv_pred)
print("Confusion Matrix = \n{}".format(cmAdv))
acAdv = accuracy_score(yAdv_test, yAdv_pred)
print("Accuracy Score = {}".format(acAdv))
print("TNR = {}".format(1878/(1878+408)))
print("TPR = {}".format(1959/(1959+282)))

Model Score = 0.9047034047034047
Confusion Matrix = 
[[1878  408]
 [ 282 1959]]
Accuracy Score = 0.8475811795891319
TNR = 0.821522309711286
TPR = 0.8741633199464525
